# Generated by Django 3.2.6 on 2025-02-10 00:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('password_hash', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('events', models.ManyToManyField(through='calendarapp.Availability', to='calendarapp.Event')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='availability',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendarapp.event'),
        ),
        migrations.AddField(
            model_name='availability',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendarapp.userprofile'),
        ),
        migrations.AddIndex(
            model_name='availability',
            index=models.Index(fields=['event', 'available_date'], name='calendarapp_event_i_635549_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='availability',
            unique_together={('user', 'event', 'available_date')},
        ),
    ]
