# Generated by Django 3.2.6 on 2025-02-12 23:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='GuestAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('available_dates', models.ManyToManyField(related_name='guest_availability', to='calendarapp.AvailableDate')),
            ],
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(default=datetime.date.today)),
                ('email', models.EmailField(default='', max_length=254)),
                ('password', models.CharField(max_length=64)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='events',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='event',
            name='creator_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='event',
            name='otp',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AddField(
            model_name='event',
            name='otp_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.DeleteModel(
            name='Availability',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.AddField(
            model_name='guestavailability',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendarapp.event'),
        ),
        migrations.AddField(
            model_name='availabledate',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendarapp.event'),
        ),
    ]
