# Generated by Django 3.2.6 on 2025-02-13 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0002_auto_20250213_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='name',
            name='access_code',
            field=models.CharField(blank=True, max_length=16, unique=True),
        ),
    ]
