# Generated by Django 3.2.6 on 2025-02-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0003_name_access_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
