# Generated by Django 3.2.6 on 2025-02-13 12:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0004_alter_name_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Name',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='creator_email',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='event',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='event',
            name='otp_verified',
        ),
        migrations.RemoveField(
            model_name='event',
            name='password_hash',
        ),
        migrations.RemoveField(
            model_name='event',
            name='slug',
        ),
        migrations.AddField(
            model_name='event',
            name='access_code',
            field=models.CharField(blank=True, max_length=16, unique=True),
        ),
        migrations.AddField(
            model_name='event',
            name='password',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
